exec: &exec
  name: build-tools/nerves-system-br
  version: 1.33.3
  elixir: 1.19.5-otp-28

version: 2.1

orbs:
  build-tools: nerves-project/build-tools@0.3.0

jobs:
  test:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - checkout
      - build-tools/install-elixir:
          version: $ELIXIR_VERSION
      - build-tools/install-hex-rebar
      - build-tools/mix-deps-get
      - run:
          name: Run tests
          command: mix test

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          exec:
            <<: *exec
          filters:
            tags:
              only: /.*/
      - build-tools/get-br-dependencies:
          exec:
            <<: *exec
          context: org-global
          filters:
            tags:
              only: /.*/
      - build-tools/build-system:
          exec:
            <<: *exec
          resource-class: large
          context: org-global
          requires:
            - build-tools/get-br-dependencies
          filters:
            tags:
              only: /.*/
      - build-tools/deploy-system:
          exec:
            <<: *exec
          context: org-global
          requires:
            - build-tools/build-system
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v.*/
